### ISSUE TITLE
Ping for Listen/Notify should support timeout cancel

### ISSUE THREAD

**Issue by wm775825** [lib/pq#1178] opened 2024-10-25 08:04 UTC
Listen/Notify provides [Ping](https://github.com/lib/pq/blob/master/notify.go#L295) to check whether long-running connection is still alive.  The client pings once and **block** forever to wait for its pong.

However, the corresponding Pong and notifications share the same [listenerConnLoop](https://github.com/lib/pq/blob/master/notify.go#L191) in one goroutine.  If it blocks when handling notifications, the client will wait forever and never return.

In the demo case, one case reads from notification channel and another pings pg server periodically. 

```go
func demo() {
	for {
		select {
		case <-stopCh:
			return
		case msg, ok := <-stream.Notify:
			// handle msg
		case <-ticker.C:
			stream.Ping()
		}
	}
}
```

When there is so many notifications in connection buffer that all go channels are full, the listenerConnLoop will block. At this time, client pings and waits for reply forever and never stops. The total system is in deadlock.

**For idiomatic Go, there is always a context.Context parameter to handle timeout. Ping should return when context timeout occurs.**

**Comment by ZhengXinwei-F** [comment] 2024-10-25 08:18
We’re also facing challenges in accurately handling `pong` responses, ensuring our system can respond correctly after a `ping` failure. 

Any insights or guidance on this issue would be extremely valuable. Thank you in advance!

**Comment by ZhengXinwei-F** [comment] 2024-10-25 08:21
@johto Are you still active in this community? I would greatly appreciate your insights on this issue.

**Comment by johto** [comment] 2024-10-25 08:47
> For idiomatic Go, there is always a context.Context parameter to handle timeout. Ping should return when context timeout occurs.

I don't disagree, but this code was written before contexts and modules were a thing in Go.  As much as it hurts to say after all the time and effort, personally I've switched to pgx.

**Comment by ZhengXinwei-F** [comment] 2024-10-25 09:02
> > For idiomatic Go, there is always a context.Context parameter to handle timeout. Ping should return when context timeout occurs.
> 
> I don't disagree, but this code was written before contexts and modules were a thing in Go. As much as it hurts to say after all the time and effort, personally I've switched to pgx.

**Thank you for your response.** 

We're also considering `pgx` as an option. I've noticed that libpq hasn’t seen new feature development for quite some time. Do you know if there are plans to introduce new features in this community, or will it primarily focus on bug fixes going forward?

**Comment by ZhengXinwei-F** [comment] 2024-10-25 09:09
> As much as it hurts to say after all the time and effort, personally I've switched to pgx.

`libpq` has been an incredibly successful community, and we've relied on it for a long time. Thank you for your contributions to it.

**Comment by johto** [comment] 2024-10-25 09:38
> Do you know if there are plans to introduce new features in this community, or will it primarily focus on bug fixes going forward?

I do not.  At this point I'm assuming only very egregious bugs would get fixed.

**Comment by johto** [comment] 2024-10-25 09:50
> libpq has been an incredibly successful community, and we've relied on it for a long time. Thank you for your contributions to it.

Thanks, I really appreciate your kind words.

> this code was written before contexts and modules were a thing in Go

FWIW I brought modules up because this library was kind of screwed by not having a proper versioning system back then.  It was impossible to fix any of the big issues because that would mean breaking backwards compatibility for practically all users.  If someone wanted to start improving things, it would be a lot easier now by just introducing a new version.  But then again, it seems like the folks at pgx are doing a fine job.

**Comment by ZhengXinwei-F** [comment] 2024-10-25 10:10
> But then again, it seems like the folks at pgx are doing a fine job.

I get it. We'll transition to using pgx in our new versions, and we'll add timeout handling for ping-pong in our legacy versions.

Thank you very much for your response.

I found exactly the answers I was looking for. I’ll be closing this issue now.

/close

**Closed** 2024-10-25 10:14 UTC

**Comment by gmbuell** [comment] 2026-08-03 02:47
I added deterministic coverage for both aspects of this report on current master `10237a6`:

- [`TestListenerNetworkFullNotifyDoesNotBlockPing`](https://github.com/gmbuell/pq/blob/1c9dd44e4cd92b7b48838b20618e55617b40078f/listener_network_regression_test.go#L392) and the adjacent reconnect test show that a full public Notify channel blocks ping replies and reconnection processing.
- [`TestListenerNetworkPingContextCancelsBlackholedQuery`](https://github.com/gmbuell/pq/blob/1c9dd44e4cd92b7b48838b20618e55617b40078f/listener_network_regression_test.go#L85) and the adjacent ListenContext test exercise cancellation against a blackholed peer without firewall setup.

The [candidate listener change](https://github.com/gmbuell/pq/commit/36ebf689fdc9bd2bf0f606e1de3713a943d424c2) decouples notification delivery and adds context-aware operations while preserving the legacy API.
