### ISSUE TITLE
sql.Open not accepting passwords with "}" 

### ISSUE THREAD

**Issue by grzegorz-bednarczyk** [lib/pq#443] opened 2016-03-03 13:53 UTC
I cannot use password that seems to be valid it contains following part: JG}ZjnD
I'me getting error like this: invalid character "}" in host name

**Comment by cbandy** [comment] 2016-03-03 14:14
Are you using quotes and/or backslashes as described in the docs?

**Comment by grzegorz-bednarczyk** [comment] 2016-03-03 14:19
Quoted like this '} changes error message to: invalid character "}" in host name.

**Comment by grzegorz-bednarczyk** [comment] 2016-03-03 14:25
Quoted like this \} changes error message to: invalid character "\\" in host name
Quoted like this '} changes error message to: invalid character "}" in host name 
I'm using URL form for connecting

**Comment by uhoh-itsmaciek** [comment] 2016-03-03 20:02
Try percent-encoding '}' (to '%7D') in the URL...

**Comment by grzegorz-bednarczyk** [comment] 2016-03-03 21:54
Tried that as well gives error: invalid URL escape "%7D"

**Comment by cbandy** [comment] 2016-03-04 01:46
Skimming RFC 3986, I don't see anything special about `}`.

**Comment by uhoh-itsmaciek** [comment] 2016-03-04 02:10
Yeah, agreed, but I've found different environments are not super-consistent with that.

Also:

```
maciek@mothra:~/code/go/src/github.com/lib/pq$ git diff
diff --git a/url_test.go b/url_test.go
index 4ff0ce0..47ead47 100644
--- a/url_test.go
+++ b/url_test.go
@@ -40,6 +40,18 @@ func TestFullParseURL(t *testing.T) {
        }
 }
 
+func TestIssue443ParseURL(t *testing.T) {
+       expected := `dbname=database host=example.com password=JG}ZjnD port=1234 user=username`
+       str, err := ParseURL("postgres://username:JG}ZjnD@example.com:1234/database")
+       if err != nil {
+               t.Fatal(err)
+       }
+
+       if str != expected {
+               t.Fatalf("unexpected result from ParseURL:\n+ %s\n- %s", str, expected)
+       }
+}
+
 func TestInvalidProtocolParseURL(t *testing.T) {
        _, err := ParseURL("http://hostname.remote")
        switch err {
maciek@mothra:~/code/go/src/github.com/lib/pq$ PGHOST=/var/run/postgresql go test github.com/lib/pq
ok  	github.com/lib/pq	0.753s
```

Can you share your full code @grzegorz-bednarczyk (obviously I recommend changing the password after you do so =) ).

**Comment by uhoh-itsmaciek** [comment] 2016-03-31 00:40
Closing since I can't reproduce this. Please reopen if you have a reproducible test case or more info.

**Closed by uhoh-itsmaciek** 2016-03-31 00:40 UTC
