### ISSUE TITLE
pq: canceling statement due to user request

### ISSUE THREAD

**Issue by azr** [lib/pq#577] opened 2017-03-12 11:27 UTC
Hello there,

Recently, I've been starting to use context queries, but not everywhere.

And in my CI I see some `pq: canceling statement due to user request` appearing where there was no problem before.

In those cases `ctx.Err()` is nil.

What is that error meaning globally ? Is this a problem in my code that was uncovered by the use of context ?? Or could the context support in pq do wrong things ?

EDIT: I'll try to make a more precise case

**Comment by azr** [comment] 2017-03-13 11:30
Oh, found this: this: https://support.chartio.com/knowledgebase/error-canceling-statement-due-to-user-request

Thought: It seems to me that when I don't use any timeout time like with a `ctx.Background()` or no context at all, then the query has 0 seconds to execute and is therefor cancelled.

**Comment by azr** [comment] 2017-03-13 11:33
This error happens when I entangle a query with a real timeout with a query that don't have any, like `Exec(` and `ExecContext(context.Background`, it seems to me that the request has zero time to execute and is therefore cancelled.

**Comment by tamird** [comment] 2017-03-13 14:08
@azr that should not happen. `context.Backrgound` has a `nil` `Done()` channel, so the query should not be subject to a timeout.

If you can provide a reproducible case, I'll look into this.

**Comment by azr** [comment] 2017-03-13 15:51
Hello @tamird 
Here is a failing test case : 

```
func TestPsql(t *testing.T) {
	setup(t, setting{})
	defer teardown(t)

	test := func() error {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second*1)
		_, err := DB.ExecContext(ctx, "SELECT NULL")
		if err != nil {
			t.Error("SELECT NULL with context failed: ", err, ctx.Err())
			cancel()
			return err
		}
		cancel()
		_, err = DB.Exec("SELECT NULL")
		if err != nil {
			t.Error("Exec SELECT NULL failed: ", err)
			return err
		}
		return nil
	}

	for i := 0; i < 10000; i++ {
		test()
	}
}
```

Both of them start failing after some looping

**Comment by tamird** [comment] 2017-03-13 16:01
Confirmed, here's a test that can be copied into go18_test.go
```go
func TestContextBroken(t *testing.T) {
	db := openTestConn(t)
	defer db.Close()

	for i := 0; i < 100; i++ {
		t.Run("", func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), time.Second*1)
			if _, err := db.ExecContext(ctx, "SELECT NULL"); err != nil {
				t.Fatal("SELECT NULL with context failed: ", err, ctx.Err())
			}
			cancel()

			if _, err := db.Exec("SELECT NULL"); err != nil {
				t.Fatal("Exec SELECT NULL failed: ", err)
			}
		})
	}
}
```

@mjibson

**Comment by azr** [comment] 2017-03-13 16:08
could reproduce with QueryRowContext and QueryRow

**Comment by tamird** [comment] 2017-03-13 16:08
I'll have a fix for this shortly.

**Comment by tamird** [comment] 2017-03-13 17:03
OK, so fixing this for `Exec{,Context}` is relatively easy, but there's a trickier case with `Query{,Context}`

Consider the following annotated example:
```go
func TestContextCancelQuery(t *testing.T) {
	db := openTestConn(t)
	defer db.Close()

	for i := 0; i < 100; i++ {
		func() {
			ctx, cancel := context.WithCancel(context.Background())
			rows, err := db.QueryContext(ctx, "select 1") // background goroutine spawned, waiting for context cancellation
			cancel() // background goroutine fires cancellation query
			if err != nil {
				t.Fatal(err)
			} else if err := rows.Close(); err != nil { // background goroutine is informed that context cancellation is no longer necessary
				t.Fatal(err)
			}
		}()

		if rows, err := db.Query("select 1"); err != nil { // cancellation query arrives during this query
			t.Fatal(err) // boom (pq: canceling statement due to user request)
		} else if err := rows.Close(); err != nil {
			t.Fatal(err)
		}
	}
}
```

Normally, `rows.Close()` occurs before context cancellation, preventing the dispatch of the cancellation query, but the above arrangement is certainly possible when timeouts are used instead of `WithCancel`.

It seems to me that we need to hold up execution of statements until all in-flight cancellations have completed. @mjibson?

**Closed** 2017-03-13 20:04 UTC

**Comment by azr** [comment] 2017-03-14 09:45
@tamird, you are the best, thanks !

**Comment by azr** [comment] 2017-05-01 14:18
Hello there, by the way, could it be possible to have a sentinel error for that "canceling statement due to user request " ?? So we don't have to do things like that: https://github.com/lib/pq/blob/472a0745531a17dbac346e828b4c60e73ddff30c/go18_test.go#L89 ?
Or may be something smarter ?

**Comment by tamird** [comment] 2017-05-01 14:27
I think that error comes from the postgres server.

**Comment by azr** [comment] 2017-05-04 17:43
So, I guess its a bad idea to try & catch it then ?

**Comment by jwilander** [comment] 2017-05-13 15:43
I believe I've found a related unhandled case that is causing me issues. If I make a query using `db.QueryContext(...)` that fails and then try a `db.Exec(...)`  or `db.Query(...)` then I'm getting the `pq: canceling statement due to user request` error.

Modifying the `TestContextCancelQuery` test to:

```
func TestContextCancelQuery(t *testing.T) {
	db := openTestConn(t)
	defer db.Close()

        // removed some code not needed to demonstrate the example

	for i := 0; i < contextRaceIterations; i++ {
		func() {
			ctx, cancel := context.WithCancel(context.Background())
			rows, err := db.QueryContext(ctx, "select * from tablethatdoesnotexist") // select from non-existent test to cause failure
			cancel()
			if err != nil {
				return // don't fail on error so we get to the query below
			} else if err := rows.Close(); err != nil {
				t.Fatal(err)
			}
		}()

		if rows, err := db.Query("select 1"); err != nil {
			t.Fatal(err)
		} else if err := rows.Close(); err != nil {
			t.Fatal(err)
		}
	}
}
```

In the test I just switched the QueryContext to fail and removed the fatal so that the test does not stop
