### ISSUE TITLE
Connections stuck in CLOSE_WAIT 

### ISSUE THREAD

**Issue by chendo** [lib/pq#342] opened 2015-02-24 06:31 UTC
We've seen some instances where the driver does not seem to be able to detect that its connections are in `CLOSE_WAIT` and given that we set `db.SetMaxOpenConns(4)`, once we have 4 connections stuck in `CLOSE_WAIT`, we need to restart the app.

This seems to happen after a sudden influx of many requests.

Our setup has the app connecting to Postgres through HAProxy which is backed by pgpool, so it's possible that it might be related to that, but the driver should still be able to detect stale connections.

**Comment by johto** [comment] 2015-02-24 08:11
> [ .. ] but the driver should still be able to detect stale connections.

It should, and it does, but it relies on the operating system telling it when a particular connection is stale.

There's nothing pq can do about this; see my answers in #335 and #319, for example.

**Comment by chendo** [comment] 2015-02-24 08:13
I see, thanks. Closing this issue.

**Comment by uhoh-itsmaciek** [comment] 2015-02-24 08:40
Stupid question (no, seriously, be forewarned: I know little about networking): if the state is CLOSE_WAIT, doesn't the OS know the connection is closing? Wouldn't this manifest as an error? CLOSE_WAIT happens when the peer has told us they would like to close the connection, no? And the OS is waiting for us to clean up? How does that fit in?

**Comment by johto** [comment] 2015-02-24 09:07
@uhoh-itsmaciek: Not a stupid question at all, actually.  You're right, if the CLOSE_WAIT state is on the client's side (i.e. `pq`'s side), any operation on the socket should result in io.EOF, which should tell database/sql to call pq.Open() again.  If that's not happening, something's likely wrong, though it's not clear where.

@chendo: Can you get a stack trace of the program when this is happening?  The easiest way, I think, is to send a SIGQUIT to kill the app; the stack trace should be written to stderr.

**Comment by chendo** [comment] 2015-02-24 09:24
@johto: I've already deployed a couple of potential workarounds, will try to reproduce tomorrow

**Comment by johto** [comment] 2015-04-24 12:10
Please reopen if you discover any evidence of `pq` not doing the right thing here.

**Closed by johto** 2015-04-24 12:10 UTC

**Comment by cihangir** [comment] 2015-09-18 06:00
hey @chendo were you able to reproduce it? what was your potential workaround?

**Comment by chendo** [comment] 2015-09-18 06:26
@cihangir the workaround was to perform a db driver 'ping' when we hit the healthcheck to keep the connection alive. Haven't had an issue since

**Comment by cihangir** [comment] 2015-09-18 06:48
alright, thanks @chendo

**Comment by peter-mogensen** [comment] 2016-08-25 10:26
But - given the scenario where the connection just dies because a NAT router drops the state - how do you know that Ping() will actually exercise all the TCP connections in the connection pool?
